# Generated by Django 5.1.3 on 2024-11-23 06:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_worker'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Address', models.TextField()),
                ('State', models.CharField(max_length=20)),
                ('Ph_no', models.CharField(max_length=10)),
                ('Email', models.EmailField(max_length=254)),
                ('document', models.FileField(upload_to='documents/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Employer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
