# Generated by Django 5.1.3 on 2024-12-01 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_openings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Age', models.CharField(max_length=3)),
                ('DOB', models.DateField()),
                ('Address', models.TextField()),
                ('Ph_no', models.CharField(max_length=10)),
                ('Job_category', models.CharField(max_length=50)),
                ('Experience', models.CharField(max_length=30)),
                ('Preffered_location', models.CharField(max_length=30)),
                ('type', models.CharField(choices=[('Full-Time', 'Full-Time'), ('Part-Time', 'Part-Time'), ('Contract', 'Contract')], max_length=10)),
                ('status', models.IntegerField(default=0)),
                ('Employer_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.employer')),
                ('Worker_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.worker')),
            ],
        ),
    ]
