# Generated by Django 5.1.3 on 2024-12-04 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('reply', models.CharField(blank=True, max_length=200, null=True)),
                ('Worker_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.worker')),
            ],
        ),
    ]
